### ISSUE TITLE
Tools for CSV data entry.

### ISSUE THREAD

**Issue by yeedle** [secretGeek/AwesomeCSV#4]
Not sure if this is out of scope, but what about tools that can be used to create (and edit) CSVs manually?

Libre/Open Office Calc, Google Sheets, Excel, etc.

**Comment by yeedle** [comment]
Thanks for your extremely thoughtful and reasonable response! I opened the issue because I have struggled with this in the past myself. Personally, I don't like to use spreadsheet software  as CSV editors because they don't respect the format, and programmatic editing is not always feasible.

The only CSV Editor which I know of and believe fits the awesome category is [Data Curator](https://github.com/ODIQueensland/data-curator) and its predecessor, Comma Chameleon. It's not perfect, but it's a thoughtful approach to data and the CSV format. So take a look and if you think it meets the awesome criteria, consider adding it. If I'll think of another tool I'll drop another comment.

**Comment by secretGeek** [comment]
I've seen Data Curator before (under the name Comma Chameleon) and note it's from my home state of Queensland. I tried using it today but it failed on the file I was working on. I'll test it again soon and try to find what's going on. So I'll leave this issue open until I've reached a conclusion either way with Data Curator.

Thank you Abraham, have a great day.
lb

**Comment by secretGeek** [comment]
closing this issue now. good discussion tho. have a good day.
